language: python
python:
- '3.6'
- '3.5'
- '3.4'
- '3.3'
- '2.7'
services:
- redis-server
env:
- TEST_HIREDIS=0
- TEST_HIREDIS=1
install:
- pip install -e .
- if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi
- if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis; fi
script: if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg
  .; else python setup.py test; fi
matrix:
  include:
  - python: '2.7'
    env: TEST_PEP8=1
  - python: '3.6'
    env: TEST_PEP8=1
deploy:
  provider: pypi
  user: "ke4roh"
  server: https://testpypi.python.org/simple/
  password:
    secure: VPLQaUuAPupHcmWeDnj3AR4PGeQx50/ZUBecYFcl18QWNPDkpoUUbJ63zpPE/Kul5+wwVsIO+48TcvRUOFzlK6HQ8D88pr+4GBlwdy20KIX7OId9/yOzj/44zPqgo1SWqUvWYwfDLd44h1aYCyWFiBmahaTbWn1QHSZhrHopMm4/DiCWQwhuSLU+wYPakqIb5+rm//LMQ0WQiYGR1pMCc45mP38yygzIhOwQsy0KbdL0WnUXwVUVIC4/jcr3Zvg818617vMKr6REGDe0o6zY2ur4K0xkzUtlIaQrTVuW38Zg3DThi4cwG7jsKwZw4cxwsovBQCZMlG1u2x4LfJBmJjVIFWBWPQ7+olpyrLGnL3exGqZKuW4sVr4kw/gHM5h83bAwsqmPVwU+bhHc4rhP9AcbqmUIjBx0alnOv3aHFy1C/p0R7orKCGtX8tqxfmgsgzjQzxf0590SwkQp6nqFMf/L4WixKevoCALD217PJE6pyLa/v5dkiDDsI2gCuZ5F1SEoiPhhjpAx9i9+QhFitKw/r+njHY/19BXLtHG7ggfyhnGYLst/5tLwGQM7ZdkcQQoViseGyWCDGp+sSKPdvkmJ1RRkcRGkxQx/DmC3jXrmoFmb6rlEnHHiUtcUa8AH/VHd4/3gIPkWojh1pGjT1qaFHICXmiGuhDB6gopjrIg=
  on:
    branch: master
